# Total: 495 rules
no_resolve: true
domain_set:
- gitlab-assets.oss-cn-hongkong.aliyuncs.com
- docker-pinata-support.s3.amazonaws.com
- github-cloud.s3.amazonaws.com
- notary-submissions-prod.s3-accelerate.amazonaws.com
- notary-submissions-prod.s3.us-west-2.amazonaws.com
- vsmarketplacebadge.apphb.com
- docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com
- default.exp-tas.com
- developers.facebook.com
- firebase.google.com
- firebase.googleapis.com
- firebaseappcheck.googleapis.com
- firebasedynamiclinks.googleapis.com
- firebasedynamiclinks-ipv4.googleapis.com
- firebasedynamiclinks-ipv6.googleapis.com
- firebaseinappmessaging.googleapis.com
- firebaseinstallations.googleapis.com
- firebaselogging.googleapis.com
- firebaselogging-pa.googleapis.com
- firebaseperusertopics-pa.googleapis.com
- firebaseremoteconfig.googleapis.com
- android.googlesource.com
- developer.microsoft.com
- download.visualstudio.microsoft.com
- amp.akamaized.net
- p-events-delivery.akamaized.net
- dtlgalleryint.cloudapp.net
- poshtestgallery.cloudapp.net
- psg-int-centralus.cloudapp.net
- psg-int-eastus.cloudapp.net
- d29vzk4ow07wi7.cloudfront.net
- rink.hockeyapp.net
- az764295.vo.msecnd.net
- appleworldwidedeveloper.hb-api.omtrdc.net
- appleworldwidedeveloper.sc.omtrdc.net
- bingsettingssearch.trafficmanager.net
- vscode-sync.trafficmanager.net
- vscode-sync-insiders.trafficmanager.net
- vscode.search.windows.net
domain_suffix_set:
- github.ai
- grazie.ai
- jetbrains.ai
- ecr.aws
- fury.blog
- github.blog
- stackmod.blog
- stackoverflow.blog
- buck.build
- fasttext.cc
- fastlane.ci
- anaconda.cloud
- youtrack.cloud
- fury.co
- stackoverflow.co
- visualstudio.co
- accountkit.com
- acpica.com
- adventofcode.com
- ampproject.com
- anaconda.com
- android.com
- androidify.com
- api-extractor.com
- developer.apple.com
- developerservices2.apple.com
- devimages-cdn.apple.com
- devstreaming-cdn.apple.com
- playgrounds-cdn.apple.com
- timestamp.apple.com
- apple-cloudkit.com
- apple-mapkit.com
- appleswift.com
- askubuntu.com
- atscaleconference.com
- bintray.com
- bitvise.com
- blogoverflow.com
- bootstrapcdn.com
- botframework.com
- braventures.com
- braveux.com
- buckbuild.com
- canonical.com
- cdnjs.com
- codethemicrobit.com
- cygwin.com
- deno.com
- dependabot.com
- docker.com
- dockerstatic.com
- embedly.com
- f8.com
- facebookconnect.com
- facebookdevelopergarage.com
- faciometrics.com
- fbf8.com
- fbinfer.com
- fblitho.com
- fbredex.com
- fbrell.com
- fightforux.com
- firebase.com
- firebaseapp.com
- firebaseio.com
- flutterapp.com
- fontawesome.com
- fortawesome.com
- forthebadge.com
- gamesstack.com
- gemfury.com
- getbootstrap.com
- git-scm.com
- gitbook.com
- github.com
- github1s.com
- githubapp.com
- githubassets.com
- githubcopilot.com
- githubhackathon.com
- githubnext.com
- githubstatus.com
- githubuniverse.com
- githubusercontent.com
- gitlab.com
- go-lang.com
- golang.com
- hashicorp.com
- hhvm.com
- insiderdevtour.com
- intellij.com
- intellinuxgraphics.com
- java.com
- jetbrains.com
- jfrog.com
- jquery.com
- jquerymobile.com
- jqueryui.com
- jsdelivr.com
- launchpadlibrarian.com
- linuxmint.com
- macruby.com
- makeitopen.com
- messengerdevelopers.com
- mcr.microsoft.com
- microsoftadc.com
- microsoftgamestack.com
- microsoftiotinsiderlabs.com
- microsoftsilverlight.com
- microsoftsqlserver.com
- mmdnn.com
- mongodb.com
- mono-project.com
- msdn.com
- msinnovationchallenge.com
- mspairlift.com
- msropendata.com
- myoctocat.com
- mysql.com
- mystrikingly.com
- nginx.com
- nodesource.com
- npmjs.com
- oneapi.com
- opengraphprotocol.com
- parse.com
- poshtestgallery.com
- pwabuilder.com
- react.com
- reactjs.com
- readthedocs.com
- readthedocs-hosted.com
- redhat.com
- redislabs.com
- regex101.com
- rocksdb.com
- serverfault.com
- sourcegraph.com
- sqlserveronlinux.com
- stackapps.com
- stackauth.com
- stackexchange.com
- stackoverflow.com
- stackoverflowbusiness.com
- stackoverflowcareers.com
- stackoverflowjobs.com
- stackoverflowsolutions.com
- stackoverflowteams.com
- stockagainstphotography.com
- strikingly.com
- strikinglycdn.com
- sublimetext.com
- superuser.com
- termius.com
- termux.com
- thegithubshop.com
- thesffblog.com
- timelinestoryteller.com
- topcoder.com
- ubuntu.com
- unity.com
- unity3d.com
- unpkg.com
- uwpcommunitytoolkit.com
- vagrantcloud.com
- vagrantup.com
- vfsforgit.com
- videojs.com
- visualstudio.com
- visualstudio-staging.com
- webobjects.com
- xamarin.com
- yarnpkg.com
- yogalayout.com
- github.community
- npm.community
- amp.dev
- dart.dev
- dartpad.dev
- flow.dev
- flutter.dev
- fury.dev
- github.dev
- githubpreview.dev
- go.dev
- pub.dev
- termux.dev
- v8.dev
- vscode.dev
- stackoverflow.email
- visualstudio.eu
- lfai.foundation
- jb.gg
- opensource.guide
- fury.help
- stackoverflow.help
- researchkit.hk
- sr.ht
- facebookappcenter.info
- microsoftreactor.info
- xposed.info
- adaptivecards.io
- atom.io
- azurecr.io
- codeforaliving.io
- compose-spec.io
- conda.io
- consul.io
- crates.io
- datalore.io
- docker.io
- firebase.io
- fury.io
- gcr.io
- gh.io
- ghcr.io
- git.io
- gitbook.io
- github.io
- gitlab.io
- graphengine.io
- hyperscan.io
- ius.io
- jenkins.io
- k8s.io
- kubernetes.io
- nomadproject.io
- packer.io
- playerjs.io
- pypa.io
- pypi.io
- qt.io
- quay.io
- readthedocs.io
- redis.io
- servicetalk.io
- shields.io
- snap-telemetry.io
- snapcraft.io
- snapstore.io
- terraform.io
- ubuntu-touch.io
- vaultproject.io
- vsassets.io
- wapm.io
- wasmer.io
- compass.is
- java
- deno.land
- embed.ly
- ogp.me
- appcenter.ms
- jwt.ms
- ampproject.net
- apisof.net
- badgen.net
- blazor.net
- devopsassessment.net
- dot.net
- facebookappcenter.net
- gitlab.net
- gitlab-static.net
- go-lang.net
- golang.net
- intellij.net
- intellinuxgraphics.net
- java.net
- jetbrains.net
- jsdelivr.net
- launchpad.net
- launchpadcontent.net
- launchpadlibrarian.net
- macruby.net
- mathoverflow.net
- mcrouter.net
- microsoftreactor.net
- microsoftsilverlight.net
- mobatek.net
- osdn.net
- ospray.net
- php.net
- remirepo.net
- researchkit.net
- rocksdb.net
- sankie.net
- shellcheck.net
- sstatic.net
- stackoverflow.net
- stacksnippets.net
- tex-talk.net
- ubuntu.net
- visualstudio.net
- vscode-cdn.net
- vscode-unpkg.net
- blob.core.windows.net
- repo.new
- 01.org
- alpinelinux.org
- ampproject.org
- anaconda.org
- apache.org
- archlinux.org
- archlinuxarm.org
- artixlinux.org
- botorch.org
- calendarserver.org
- carekit.org
- centos.org
- chocolatey.org
- clearlinux.org
- clojure.org
- cnpmjs.org
- codeberg.org
- componentkit.org
- cpan.org
- cups.org
- cython.org
- dartlang.org
- debian.org
- dotdeb.org
- draftjs.org
- electronjs.org
- elixir-lang.org
- elrepo.org
- erlang.org
- facebookappcenter.org
- fedoraforum.org
- fedoramagazine.org
- fedorapeople.org
- fedoraproject.org
- ffmpeg.org
- flathub.org
- flatpak.org
- flow.org
- flowtype.org
- foundationdb.org
- freebsd.org
- frescolib.org
- gentoo.org
- getcomposer.org
- getfedora.org
- getzola.org
- gnu.org
- go-lang.org
- godoc.org
- golang.org
- hacklang.org
- haskell.org
- haskellstack.org
- intellij.org
- jfrog.org
- js.org
- jupyter.org
- kali.org
- kernel.org
- kotlinlang.org
- launchpadlibrarian.org
- lede-project.org
- linux.org
- linuxfoundation.org
- linuxfromscratch.org
- lua.org
- macosforge.org
- macports.org
- macruby.org
- mariadb.org
- mcrouter.org
- metacpan.org
- microbit.org
- microsoftreactor.org
- microsoftsilverlight.org
- mingw.org
- mochajs.org
- mongodb.org
- nginx.org
- nixos.org
- nodejs.org
- notepad-plus-plus.org
- npmjs.org
- nuget.org
- nugettest.org
- opengraphprotocol.org
- openjsf.org
- openresty.org
- openssl.org
- opensuse.org
- opentranslatorstothings.org
- openvinotoolkit.org
- openwrt.org
- ospray.org
- packagist.org
- pcre.org
- perl.org
- phantomjs.org
- piwheels.org
- polymer-project.org
- polymerproject.org
- postgresql.org
- putty.org
- pycon.org
- pypi.org
- pyrobot.org
- python.org
- pythonhosted.org
- qt-project.org
- r-project.org
- raspberrypi.org
- raspbian.org
- reactjs.org
- readthedocs.org
- recoiljs.org
- redhat.org
- researchandcare.org
- researchkit.org
- rocksdb.org
- rpmfusion.org
- ruby-lang.org
- rubygems.org
- rust-lang.org
- scala-lang.org
- scala-sbt.org
- scientificlinux.org
- sourcehut.org
- sqlite.org
- stackage.org
- swift.org
- termux.org
- ubuntuforums.org
- v8project.org
- vfsforgit.org
- videolan.org
- vim.org
- webkit.org
- webkitgtk.org
- wireshark.org
- wpewebkit.org
- x.org
- zsh.org
- codeberg.page
- modperl.pl
- hex.pm
- hexdocs.pm
- docs.rs
- rustup.rs
- esm.run
- brew.sh
- scoop.sh
- jetbrains.space
- jetbrains.team
- dev.to
- fastlane.tools
- researchkit.tv
- visualstudio.co.uk
- greenend.org.uk
domain_regex_set:
- .+\.dkr\.ecr\.[^\.]+\.amazonaws\.com$
- ^github-production-release-asset-[0-9a-zA-Z]{6}\.s3\.amazonaws\.com$
