from rule_set.models import (
    DomainSetResource,
    GeoIPOption,
    MaxMindDBResource,
    Option,
    ProcessingOption,
    RuleSetResource,
    SerializationOption,
    SourceModel,
    SourceReference,
    V2rayDomainAttr,
    V2rayDomainOption,
    V2rayDomainResource,
)

sources = [
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/global.conf"),
            RuleSetResource(source="sources/global"),
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/python"
            ),
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/rust"
            ),
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/flutter"
            ),
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/paypal"
            ),
            SourceReference(target="dev"),
        ],
        name="global",
        option=Option(
            processing=ProcessingOption(
                exclude_rule_types=["ip_trie", "ip_trie6", "ip_asn"],
            ),
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.EXCLUDE_ATTRS("ads"),
            ),
        ),
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf"
            )
        ],
        name="adblock/sukka/sukka-reject-no-drop",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/reject-drop.conf"
            )
        ],
        name="adblock/sukka/sukka-reject-drop",
    ),
    SourceModel(
        resources=[
            DomainSetResource(
                source="https://ruleset.skk.moe/List/domainset/reject.conf"
            ),
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/reject.conf"),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/reject.conf"),
        ],
        name="adblock/sukka/sukka-reject",
        option=Option(
            processing=ProcessingOption(
                exclude_suffixes=[
                    "juejin.cn",
                    "juejin.im",
                ]
            ),
        ),
    ),
    SourceModel(
        resources=[
            DomainSetResource(
                source="https://ruleset.skk.moe/List/domainset/reject_extra.conf"
            )
        ],
        name="adblock/sukka/sukka-reject-extra",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list"
            )
        ],
        name="adblock/cats-team-ad",
    ),
    SourceModel(
        resources=[
            DomainSetResource(
                source="https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt"
            )
        ],
        name="adblock/anti-ad",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://raw.githubusercontent.com/EAlyce/conf/main/Rule/FQNovelAdvertising.list"
            )
        ],
        name="adblock/fqnovel-ad",
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/ai.conf")
        ],
        name="ai",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/apple_cdn.conf"
            ),
            DomainSetResource(
                source="https://ruleset.skk.moe/List/domainset/apple_cdn.conf"
            ),
        ],
        name="apple/apple-cdn",
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/apple_cn.conf")
        ],
        name="apple/apple-cn",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/apple_services.conf"
            ),
        ],
        name="apple/apple-services",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf"
            )
        ],
        name="microsoft/microsoft-cdn",
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/microsoft.conf")
        ],
        name="microsoft/microsoft",
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/telegram.conf"),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/telegram.conf"),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/telegram_asn.conf"),
        ],
        name="telegram",
    ),
    SourceModel(
        resources=[
            DomainSetResource(
                source="https://ruleset.skk.moe/List/domainset/speedtest.conf"
            )
        ],
        name="speedtest",
    ),
    SourceModel(
        resources=[RuleSetResource(source="sources/global/dropbox.txt")],
        name="dropbox",
    ),
    SourceModel(
        resources=[
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/steam"
            )
        ],
        name="steam/steam-cn",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.ATTRS("cn"),
            ),
        ),
    ),
    SourceModel(
        resources=[
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/steam"
            )
        ],
        name="steam/steam",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.NO_ATTR(),
            ),
        ),
    ),
    SourceModel(
        resources=[
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-game-platforms-download"
            )
        ],
        name="game/game-download-cn",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.ATTRS("cn"),
            ),
        ),
    ),
    SourceModel(
        resources=[
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-game-platforms-download"
            ),
            RuleSetResource(source="sources/game/download.txt"),
        ],
        name="game/game-download",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.NO_ATTR(),
            ),
        ),
    ),
    SourceModel(
        resources=[
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-games-cn"
            ),
            RuleSetResource(source="sources/game/cn.txt"),
            SourceReference(target="steam/steam-cn"),
        ],
        name="game/game-cn",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.EXCLUDE_ATTRS(["!cn", "ads"]),
                exclude_includes=["4399", "cowlevel", "tgbus", "vrzwk"],
            ),
        ),
    ),
    SourceModel(
        resources=[
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-games-!cn"
            ),
            RuleSetResource(source="sources/game/global.txt"),
        ],
        name="game/game",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.EXCLUDE_ATTRS(["cn", "ads"]),
            ),
        ),
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/download.conf"),
            DomainSetResource(
                source="https://ruleset.skk.moe/List/domainset/download.conf"
            ),
        ],
        name="download",
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/cdn.conf"),
            DomainSetResource(source="https://ruleset.skk.moe/List/domainset/cdn.conf"),
        ],
        name="cdn",
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/domestic.conf"),
            RuleSetResource(source="sources/direct/direct.txt"),
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/amazon"
            ),
            SourceReference(target="game/game-cn"),
            SourceReference(target="game/game-download-cn"),
        ],
        name="direct",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.ATTRS("cn"),
            ),
        ),
    ),
    SourceModel(
        resources=[
            V2rayDomainResource(
                source="https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-dev"
            )
        ],
        name="dev",
        option=Option(
            v2ray_domain=V2rayDomainOption(
                attrs=V2rayDomainAttr.EXCLUDE_ATTRS(["cn", "ads"]),
            ),
        ),
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/lan.conf"),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/lan.conf"),
        ],
        name="lan",
        option=Option(
            serialization=SerializationOption(no_resolve=False),
        ),
    ),
    SourceModel(
        resources=[RuleSetResource(source="sources/global/ehentai.txt")],
        name="e-hentai",
    ),
    SourceModel(
        resources=[RuleSetResource(source="sources/global/reddit.txt")],
        name="reddit",
    ),
    SourceModel(
        resources=[RuleSetResource(source="sources/direct/anime.txt")],
        name="anime",
    ),
    SourceModel(
        resources=[
            MaxMindDBResource(
                source="https://raw.githubusercontent.com/NobyDa/geoip/release/Private-GeoIP-CN.mmdb"
            )
        ],
        name="cn-ip/cn-nobyda",
        option=Option(
            serialization=SerializationOption(no_resolve=False),
            geo_ip=GeoIPOption(country_code="CN"),
        ),
    ),
    SourceModel(
        resources=[
            MaxMindDBResource(
                source="https://github.com/xream/geoip/releases/latest/download/ipinfo.country.mmdb"
            )
        ],
        name="cn-ip/cn-ipinfo",
        option=Option(
            serialization=SerializationOption(no_resolve=False),
            geo_ip=GeoIPOption(country_code="CN"),
        ),
    ),
    SourceModel(
        resources=[
            MaxMindDBResource(
                source="https://github.com/xream/geoip/releases/latest/download/ip2location.country.mmdb"
            )
        ],
        name="cn-ip/cn-ip2location",
        option=Option(
            serialization=SerializationOption(no_resolve=False),
            geo_ip=GeoIPOption(country_code="CN"),
        ),
    ),
    SourceModel(
        resources=[
            MaxMindDBResource(
                source="https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb"
            )
        ],
        name="cn-ip/cn-alecthw",
        option=Option(
            serialization=SerializationOption(no_resolve=False),
            geo_ip=GeoIPOption(country_code="CN"),
        ),
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/china_ip.conf"),
            RuleSetResource(
                source="https://ruleset.skk.moe/List/ip/china_ip_ipv6.conf"
            ),
        ],
        name="cn-ip/cn-sukka",
        option=Option(
            serialization=SerializationOption(no_resolve=False),
            geo_ip=GeoIPOption(country_code="CN"),
        ),
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/stream_us.conf"
            ),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/stream_us.conf"),
        ],
        name="stream/stream-us",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/stream_eu.conf"
            ),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/stream_eu.conf"),
        ],
        name="stream/stream-eu",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/stream_jp.conf"
            ),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/stream_jp.conf"),
        ],
        name="stream/stream-jp",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/stream_kr.conf"
            ),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/stream_kr.conf"),
        ],
        name="stream/stream-kr",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/stream_hk.conf"
            ),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/stream_hk.conf"),
        ],
        name="stream/stream-hk",
    ),
    SourceModel(
        resources=[
            RuleSetResource(
                source="https://ruleset.skk.moe/List/non_ip/stream_tw.conf"
            ),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/stream_tw.conf"),
        ],
        name="stream/stream-tw",
    ),
    SourceModel(
        resources=[
            RuleSetResource(source="https://ruleset.skk.moe/List/non_ip/stream.conf"),
            RuleSetResource(source="https://ruleset.skk.moe/List/ip/stream.conf"),
        ],
        name="stream/stream",
    ),
    SourceModel(
        resources=[RuleSetResource(source="sources/direct/process.txt")],
        name="direct/process",
    ),
    SourceModel(
        resources=[
            SourceReference(target="global"),
            SourceReference(target="cdn"),
            SourceReference(target="download"),
            SourceReference(target="telegram"),
            SourceReference(target="stream/stream"),
            SourceReference(target="game/game"),
            SourceReference(target="game/game-download"),
        ],
        name="global-all",
    ),
]


for source in sources:
    for resource in source.resources:
        if isinstance(resource, SourceReference):
            continue
        if str(resource.source).startswith("https://ruleset.skk.moe"):
            source.option.processing.exclude_suffixes.extend(
                [
                    "7h1s_rul35et_i5_mad3_by_5ukk4w-ruleset.skk.moe",
                    "th1s_rule5et_1s_m4d3_by_5ukk4w_ruleset.skk.moe",
                    "this_ruleset_is_made_by_sukkaw.ruleset.skk.moe",
                ],
            )
            break
