# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/serialize/geoip/geoip.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'src/serialize/geoip/geoip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsrc/serialize/geoip/geoip.proto\"\"\n\x04\x43IDR\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0e\n\x06prefix\x18\x02 \x01(\r\"I\n\x05GeoIP\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x13\n\x04\x63idr\x18\x02 \x03(\x0b\x32\x05.CIDR\x12\x15\n\rinverse_match\x18\x03 \x01(\x08\"\"\n\tGeoIPList\x12\x15\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x06.GeoIPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.serialize.geoip.geoip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CIDR']._serialized_start=35
  _globals['_CIDR']._serialized_end=69
  _globals['_GEOIP']._serialized_start=71
  _globals['_GEOIP']._serialized_end=144
  _globals['_GEOIPLIST']._serialized_start=146
  _globals['_GEOIPLIST']._serialized_end=180
# @@protoc_insertion_point(module_scope)
