from model import SerializeFormat, SourceModel, Option

SOURCES = [
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf",
        target_path="Sukka-ad-reject-no-drop",
        include=[SerializeFormat.Surge, SerializeFormat.Loon],
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/reject-drop.conf",
        target_path="Sukka-ad-reject-drop",
        exclude=[SerializeFormat.Egern, SerializeFormat.Sing_Box],
    ),
    SourceModel(
        resources=[
            ("https://ruleset.skk.moe/List/domainset/reject.conf", "DOMAIN-SET"),
            "https://ruleset.skk.moe/List/non_ip/reject.conf",
            "https://ruleset.skk.moe/List/ip/reject.conf",
        ],
        target_path="Sukka-ad",
        include=[SerializeFormat.Surge, SerializeFormat.Loon],
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf",
            ("https://ruleset.skk.moe/List/domainset/reject.conf", "DOMAIN-SET"),
            "https://ruleset.skk.moe/List/non_ip/reject.conf",
            "https://ruleset.skk.moe/List/ip/reject.conf",
        ],
        target_path="Sukka-ad",
        include=SerializeFormat.Clash,
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf",
            "https://ruleset.skk.moe/List/non_ip/reject-drop.conf",
            ("https://ruleset.skk.moe/List/domainset/reject.conf", "DOMAIN-SET"),
            "https://ruleset.skk.moe/List/non_ip/reject.conf",
            "https://ruleset.skk.moe/List/ip/reject.conf",
        ],
        target_path="Sukka-ad",
        include=[SerializeFormat.Egern, SerializeFormat.Sing_Box],
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list",
        target_path="Cats-ad",
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt",
            "DOMAIN-SET",
        ),
        target_path="Anti-ad",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Privacy/Privacy_All.list",
        target_path="Privacy",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list",
        target_path="OpenAI",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/apple_cdn.conf",
        target_path="Apple_cdn",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/apple_cn.conf",
        target_path="Apple_cn",
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/apple_services.conf",
            # "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple_All.list",
        ],
        target_path="Apple_services",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf",
        target_path="Microsoft_cdn",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/microsoft.conf",
        target_path="Microsoft",
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/telegram.conf",
            "https://ruleset.skk.moe/List/ip/telegram.conf",
        ],
        target_path="Telegram",
    ),
    SourceModel(
        resources=(
            "https://ruleset.skk.moe/List/domainset/speedtest.conf",
            "DOMAIN-SET",
        ),
        target_path="Speedtest",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Dropbox/Dropbox.list",
        target_path="Dropbox",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/SteamCN/SteamCN.list",
        target_path="SteamCN",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Steam/Steam.list",
        target_path="Steam",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Game/GameDownloadCN/GameDownloadCN.list",
        target_path="GameDownloadCN",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Game/GameDownload/GameDownload.list",
        target_path="GameDownload",
    ),
    SourceModel(
        resources=[
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Game/Game.list",
            "sources/game.txt",
            "sources/apex.txt",
        ],
        target_path="Game",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/domestic.conf",
        target_path="Domestic",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_All.list",
        target_path="Global",
        option=Option(
            exclude_rule_types=["ip_cidr", "ip_cidr6", "ip_asn"],
        ),
    ),
    SourceModel(
        resources=[
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Instagram/Instagram.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Discord/Discord.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitHub/GitHub.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitLab/GitLab.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/IMDB/IMDB.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PayPal/PayPal.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Pixiv/Pixiv.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Patreon/Patreon.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Python/Python.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Tmdb/Tmdb.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitch/Twitch.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Vercel/Vercel.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OP/OP.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cloudflare/Cloudflare.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Oracle/Oracle.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Amazon/Amazon.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Mozilla/Mozilla.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Docker/Docker.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitBook/GitBook.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Npmjs/Npmjs.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Notion/Notion.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Spotify/Spotify.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Akamai/Akamai.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Dropbox/Dropbox.list",
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Reddit/Reddit.list",
            "my-rules/proxy.txt",
        ],
        target_path="Proxy",
        option=Option(
            exclude_suffixes=[".cn"],
            exclude_rule_types=["ip_cidr", "ip_cidr6", "ip_asn"],
        ),
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt",
        target_path="GFW",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan_Resolve.list",
        target_path="Lan",
        option=Option(no_resolve=False),
    ),
    SourceModel(resources="my-rules", option=Option(clash_optimize=False)),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/EHGallery/EHGallery.list",
        target_path="ExHentai",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Reddit/Reddit.list",
        target_path="Reddit",
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/NobyDa/geoip/release/Private-GeoIP-CN.mmdb",
            "MaxMind DB",
        ),
        target_path="CN",
        option=Option(no_resolve=False, geo_ip_country_code="CN"),
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OneDrive/OneDrive.list",
        target_path="OneDrive",
    ),
]
