from model import SerializeFormat, SourceModel, Option, V2rayDomainAttr

SOURCES = [
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf",
        target_path="adblock/sukka/reject-no-drop",
        include=[SerializeFormat.Surge, SerializeFormat.Loon],
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/reject-drop.conf",
        target_path="adblock/sukka/reject-drop",
        exclude=[SerializeFormat.Egern, SerializeFormat.Sing_Box],
    ),
    SourceModel(
        resources=[
            ("https://ruleset.skk.moe/List/domainset/reject.conf", "DOMAIN-SET"),
            "https://ruleset.skk.moe/List/non_ip/reject.conf",
            "https://ruleset.skk.moe/List/ip/reject.conf",
        ],
        target_path="adblock/sukka/reject",
    ),
    SourceModel(
        resources=(
            "https://ruleset.skk.moe/List/domainset/reject_extra.conf",
            "DOMAIN-SET",
        ),
        target_path="adblock/sukka/reject-extra",
    ),
    SourceModel(
        resources="https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list",
        target_path="adblock/cats-team",
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt",
            "DOMAIN-SET",
        ),
        target_path="adblock/anti-ad",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/ai.conf", target_path="ai"
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/apple_cdn.conf",
        target_path="apple/cdn",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/apple_cn.conf",
        target_path="apple/cn",
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/apple_services.conf",
        ],
        target_path="apple/services",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf",
        target_path="microsoft/cdn",
    ),
    SourceModel(
        resources="https://ruleset.skk.moe/List/non_ip/microsoft.conf",
        target_path="microsoft/global",
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/telegram.conf",
            "https://ruleset.skk.moe/List/ip/telegram.conf",
        ],
        target_path="telegram",
    ),
    SourceModel(
        resources=(
            "https://ruleset.skk.moe/List/domainset/speedtest.conf",
            "DOMAIN-SET",
        ),
        target_path="speedtest",
    ),
    SourceModel(
        resources="sources/global/dropbox.txt",
        target_path="dropbox",
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/steam",
            "V2RAY-DOMAIN",
        ),
        target_path="steam/cn",
        option=Option(v2ray_domain_attrs=V2rayDomainAttr.ATTRS("cn")),
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/steam",
            "V2RAY-DOMAIN",
        ),
        target_path="steam/global",
        option=Option(v2ray_domain_attrs=V2rayDomainAttr.NO_ATTR()),
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-game-platforms-download",
            "V2RAY-DOMAIN",
        ),
        target_path="game/download-cn",
        option=Option(v2ray_domain_attrs=V2rayDomainAttr.ATTRS("cn")),
    ),
    SourceModel(
        resources=[
            (
                "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-game-platforms-download",
                "V2RAY-DOMAIN",
            ),
            "sources/game/download.txt",
        ],
        target_path="game/download",
        option=Option(v2ray_domain_attrs=V2rayDomainAttr.NO_ATTR()),
    ),
    SourceModel(
        resources=[
            (
                "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-games-cn",
                "V2RAY-DOMAIN",
            ),
            "sources/game/cn.txt",
            "rule-set/surge/steam/cn.list",
        ],
        target_path="game/cn",
        option=Option(
            v2ray_domain_attrs=V2rayDomainAttr.EXCLUDE_ATTRS("!cn"),
            v2ray_domain_exclude_includes=["4399", "cowlevel", "tgbus", "vrzwk"],
        ),
    ),
    SourceModel(
        resources=[
            (
                "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-games-!cn",
                "V2RAY-DOMAIN",
            ),
            "sources/game/global.txt",
        ],
        target_path="game/global",
        option=Option(
            v2ray_domain_attrs=V2rayDomainAttr.EXCLUDE_ATTRS("cn"),
        ),
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/domestic.conf",
            "sources/direct.txt",
        ],
        target_path="direct",
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/global.conf",
            "sources/global",
        ],
        target_path="global",
        option=Option(
            exclude_suffixes=[
                ".cn",
            ],
            exclude_keywords=[
                "-cn.",
            ],
            exclude_rule_types=["ip_cidr", "ip_cidr6", "ip_asn"],
            optimize_domains_by_keyword=True,
        ),
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/non_ip/lan.conf",
            "https://ruleset.skk.moe/List/ip/lan.conf",
        ],
        target_path="lan",
        option=Option(no_resolve=False),
    ),
    SourceModel(resources="sources/my-rules", option=Option(clash_optimize=False)),
    SourceModel(
        resources="sources/global/ehentai.txt",
        target_path="exhentai",
    ),
    SourceModel(
        resources="sources/global/reddit.txt",
        target_path="reddit",
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/NobyDa/geoip/release/Private-GeoIP-CN.mmdb",
            "MaxMind DB",
        ),
        target_path="cn-ip/nobyda",
        option=Option(no_resolve=False, geo_ip_country_code="CN"),
    ),
    SourceModel(
        resources=(
            "https://github.com/xream/geoip/releases/latest/download/ipinfo.country.mmdb",
            "MaxMind DB",
        ),
        target_path="cn-ip/ipinfo",
        option=Option(no_resolve=False, geo_ip_country_code="CN"),
    ),
    SourceModel(
        resources=(
            "https://github.com/xream/geoip/releases/latest/download/ip2location.country.mmdb",
            "MaxMind DB",
        ),
        target_path="cn-ip/ip2location",
        option=Option(no_resolve=False, geo_ip_country_code="CN"),
    ),
    SourceModel(
        resources=(
            "https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb",
            "MaxMind DB",
        ),
        target_path="cn-ip/alecthw",
        option=Option(no_resolve=False, geo_ip_country_code="CN"),
    ),
    SourceModel(
        resources=[
            "https://ruleset.skk.moe/List/ip/china_ip.conf",
            "https://ruleset.skk.moe/List/ip/china_ip_ipv6.conf",
        ],
        target_path="cn-ip/sukka",
        option=Option(no_resolve=False, geo_ip_country_code="CN"),
    ),
]
