from model import ClientEnum, SourceModel

SOURCES = [
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf",
        filename="Sukka-ad-reject-no-drop",
        exclude=ClientEnum.Egern,
    ),
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/reject-drop.conf",
        filename="Sukka-ad-reject-drop",
        exclude=ClientEnum.Egern,
    ),
    SourceModel(
        urls=[
            "https://ruleset.skk.moe/List/domainset/reject.conf",
            "https://ruleset.skk.moe/List/non_ip/reject.conf",
            "https://ruleset.skk.moe/List/ip/reject.conf",
        ],
        filename="Sukka-ad",
        exclude=ClientEnum.Egern,
    ),
    SourceModel(
        urls=[
            "https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf",
            "https://ruleset.skk.moe/List/non_ip/reject-drop.conf",
            "https://ruleset.skk.moe/List/domainset/reject.conf",
            "https://ruleset.skk.moe/List/non_ip/reject.conf",
            "https://ruleset.skk.moe/List/ip/reject.conf",
        ],
        filename="Sukka-ad",
        include=ClientEnum.Egern,
    ),
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/apple_cdn.conf",
        filename="Apple_cdn",
    ),
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/apple_cn.conf",
        filename="Apple_cn",
    ),
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/apple_services.conf",
        filename="Apple_services",
    ),
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf",
        filename="Microsoft_cdn",
    ),
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/microsoft.conf",
        filename="Microsoft",
    ),
    SourceModel(
        urls=[
            "https://ruleset.skk.moe/List/non_ip/telegram.conf",
            "https://ruleset.skk.moe/List/ip/telegram.conf",
        ],
        filename="Telegram",
    ),
    SourceModel(
        urls="https://raw.githubusercontent.com/KotaHv/SukkaW-Surge/release/List/domainset/speedtest.conf",
        filename="Speedtest",
    ),
    SourceModel(
        urls="https://ruleset.skk.moe/List/non_ip/domestic.conf", filename="Domestic"
    ),
    SourceModel(
        urls="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_All.list",
        filename="Global",
    ),
    SourceModel(
        urls="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan_Resolve.list",
        filename="Lan",
        no_resolve=False,
    ),
]
